---
output: 
  html_document:
    css: styles.css
params:
  site: "FRAZ"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')
```

```{r imports, echo = FALSE, results = 'hide', include = F}
library(tidyverse)
library(knitr)
library(kableExtra)

filepath <- "D:/NETN/Monitoring_Projects/Freshwater_Wetland/EPA_NWCA/2016_Data/2021_release/ACAD_only"
filenames <- list.files(filepath)
list.files(filepath)
site_df <- data.frame(Local_Name = c("DUCK", "WMTN", "BIGH", "GILM", "LIHU", "NEMI", "GRME", "HEBR", "HODG", "FRAZ"),
                      Full_Name = c("Duck Pond Peatland", "Western Mountain Swamp", "Big Heath", "Gilmore Meadow",
                                    "Little Hunter Brook", "New Mills Meadow - NW", "Great Meadow (IAH)", "Heath Brook",
                                    "Hodgdon Swamp", "Frazer Fen"),
                      NWCA_codes = c("NWCA16-R301", "NWCA16-R302", "NWCA16-R303", "NWCA16-R304", "NWCA16-R305",
                                     "NWCA16-R306", "NWCA16-R307", "NWCA16-R308", "NWCA16-R309", "NWCA16-R310"))

# Import NWCA data and drop columns with all NA
import_csv <- function(filename){
  df <- read.csv(paste0(filepath, "/", filename))
  df <- df[,colSums(is.na(df)) < nrow(df)]
  return(df)
}

prep_data <- function(df, site){
  df <- df %>% filter(Local_Name == site) %>% select(-SITE_ID, -Local_Name)
  df <- df[,colSums(is.na(df)) < nrow(df)]
  return(df)
}

make_long <- function(df, data_type){
  col_names <- names(df %>% select(-SITE_ID, -Local_Name))
  df_long <- df %>% mutate_at(all_of(col_names), as.character) %>% 
                    pivot_longer(cols = all_of(col_names),
                                 names_to = "Metric", 
                                 values_to = "Value",
                                 values_drop_na = TRUE) %>% 
                    mutate(Type = data_type) %>% 
                    select(SITE_ID, Local_Name, Type, Metric, Value)
  return(df_long)
  
}


make_long_buff <- function(df, data_type){
  col_names <- names(df %>% select(-SITE_ID, -Local_Name, -Plot))
  df_long <- df %>% mutate_at(all_of(col_names), as.character) %>% 
                    pivot_longer(cols = all_of(col_names),
                                 names_to = "Metric", 
                                 values_to = "Value",
                                 values_drop_na = TRUE) %>% 
                    select(SITE_ID, Local_Name, Plot, Metric, Value)
  return(df_long)
  
}

drop_na <- function(x){ifelse(is.na(x), "", paste0(x, ", "))}
drop_na2 <- function(x){ifelse(is.na(x), "", paste0(x))}
drop_na_col <- function(x){ifelse(is.na(x), "", paste0(x, ": "))}

# Site characterization data
AAchar <- import_csv(filenames[1])[, c("SITE_ID", "Local_Name" ,"AA_AREA", "AA_CENTER",
                                       "AA_LAT", "AA_LON", "AA_LAYOUT", "AA_POINT",
                                       "HGM_CLASS", "DEPRESSION", "FLATS", "RIVERINE", "SLOPE")]

AAhydro_source <- import_csv(filenames[2])[, c("SITE_ID", "Local_Name", "OUTFLOWS", "INFLOW_PRESENT", "PRECIP_PRESENT",
                                               "GRDWATER_PRESENT", "INFLOW_RANK", "PRECIP_RANK", "GRDWATER_RANK")]

AAhydro_ind <- import_csv(filenames[4]) %>% select(-UID, -(PUBLICATION_DATE:DATE_COL), -VALXSITE)


waterchar <- import_csv(filenames[19]) %>% select("SITE_ID", "Local_Name", "WATER_PRESENCE", "WATER_TYPE", 
                                                  "SW_DEPTH_MAX", "SW_GREATER_1M", "SW_COVERAGE", "COLOR_BROWN",
                                                  "CLARITY_CLEAR", "CLARITY_STAINED", "VEG_PRESENT", "SUB_MUCK",
                                                  "SUB_ORGANIC", "SMELL_NONE", "SURFACE_FLOC", "SURFACE_SHEEN", 
                                                  "SURFACE_VEGETATION")

AAchar_long <- rbind(make_long(AAchar, "AA Characterization"),
                     make_long(AAhydro_source, "AA Water Sources"),
                     make_long(AAhydro_ind, "AA Hydrology Indicators"))

waterchar <- waterchar %>% mutate(surf_water = ifelse(WATER_PRESENCE == "Y", "SAMPLED", "NOT SAMPLED"),
                                  veg_present = ifelse(VEG_PRESENT == "Y", "VEG PRESENT", NA),
                                  surf_veg = ifelse(SURFACE_VEGETATION == "VEGETATION", "ROOTED VEGETATION", NA),
                                  water_char = paste0(drop_na(COLOR_BROWN), drop_na(CLARITY_CLEAR), drop_na(CLARITY_STAINED), 
                                                     drop_na(SUB_MUCK), drop_na(SUB_ORGANIC), drop_na(SURFACE_FLOC), 
                                                     drop_na(SURFACE_SHEEN), drop_na(veg_present), drop_na(surf_veg)),
                                  Characteristics = substr(water_char, 1, nchar(water_char) - 2)) %>% 
                          select(SITE_ID, Local_Name, surf_water, WATER_TYPE, SW_DEPTH_MAX, SW_COVERAGE, Characteristics) %>% 
                          rename(Sample_Info = surf_water,
                                 Max_Depth_cm = SW_DEPTH_MAX,
                                 Pct_Cov_AA = SW_COVERAGE)


buffer_stress <- import_csv(filenames[6]) %>% select(SITE_ID, Local_Name, LOCATION, PLOT, RES_ROAD, RES_ROAD_COMMENT,
                                                     HAB_SELECTIVE_CUT, HAB_SELECTIVE_CUT_COMMENT, DATA_NOTES) %>% 
                                              mutate(Plot = substr(paste0(drop_na2(LOCATION), drop_na2(PLOT)),1,2)) %>% 
                                              select(-LOCATION, -PLOT, SITE_ID, Local_Name, 
                                                     Plot, RES_ROAD:HAB_SELECTIVE_CUT_COMMENT) 

buffer_long <- make_long_buff(buffer_stress) %>% 
               mutate(Metric = ifelse(Metric == "DATA_NOTES", paste0("NONE"), Metric),
                      Plot = ifelse(Plot == "", "NA", Plot)) %>% 
               filter(Local_Name == params$site) %>% select(-SITE_ID, -Local_Name, -Value)

vegplot_layout <- import_csv(filenames[7]) %>% select(SITE_ID, Local_Name, OBSTACLE, OBSTACLE_DEEP) %>% 
                                               mutate(veg_layout = ifelse(is.na(OBSTACLE), "STANDARD", 
                                                                          paste0(drop_na_col(OBSTACLE), 
                                                                                 drop_na2(OBSTACLE_DEEP)))) %>% 
                                               select(SITE_ID, Local_Name, veg_layout)


```

```{r kable_tables, echo = F, include = F, results = 'hide'}
AAsite <- prep_data(AAchar_long, params$site)

row_changes_AA <- sapply(1:nrow(AAsite), function(x){
  check = ifelse(AAsite$Type[x] != AAsite$Type[x + 1], x, NA)
  }) %>% data.frame() %>% na.omit(.) 

AAchar_kbl <- kable(AAsite, caption = "<h4>AA Characterization</h4>",
                    col.names = c("Data Type", "Metric", "Value"),
                    format = "html", align = 'c') %>% 
              kable_styling(fixed_thead = TRUE, bootstrap_options = c('condensed'), 
                            full_width = FALSE, position = 'left', font_size = 12) %>%
              column_spec(1:3, extra_css = "border-left: 1px solid #000000; border-right: 1px solid #000000;") %>% 
              collapse_rows(1, valign = 'top') %>% 
              row_spec(2:(nrow(AAsite)-1), extra_css = "border-bottom: 0.5px solid #CACACA;") %>% 
              row_spec(row_changes_AA[,1], extra_css = "border-bottom: 1px solid #000000;") %>% 
              row_spec(0, extra_css = 'border-bottom: 1px solid #000000;') %>% 
              row_spec(nrow(AAsite), extra_css = 'border-bottom: 1px solid #000000;', hline_after = T) 

water_site <- waterchar %>% filter(Local_Name == params$site)

waterchar_kbl <- if(water_site$Sample_Info == "SAMPLED"){
                    water_long <- make_long(water_site, "Water Sample Info") %>% select(-SITE_ID, -Local_Name, -Type)
                    kable(water_long, format = 'html', align = 'c', caption = "<h4>Water Sample Info</h4>",
                          col.names = c("Metric", "Value")) %>% 
                    kable_styling(fixed_thead = TRUE, bootstrap_options = 'condensed',
                                  full_width = TRUE, position = 'right', font_size = 12) %>% 
                    row_spec(0:nrow(water_long), extra_css = 'border-bottom: 1px solid #000000;') %>% 
                    column_spec(1:2, extra_css = "border-left: 1px solid #000000; border-right: 1px solid #000000;") 
} else {            water_long <- make_long(water_site, "Water Sample Info") %>% select(Value) %>% slice(1)
                    kable(water_long, format = 'html', align = 'c', caption = "<h4>Water Sample Info</h4>",
                          col.names = c("")) %>% 
                    kable_styling(fixed_thead = TRUE, bootstrap_options = 'condensed',
                                  full_width = TRUE, position = 'right', font_size = 12) %>% 
                    row_spec(0:1, extra_css = 'border-bottom: 1px solid #000000;') %>% 
                    column_spec(1, border_left = T, border_right = T)}

buffer_kbl <- kable(buffer_long, format = "html", align = "c", caption = "<h4>Buffer Stressors</h4>",
                    col.names = c("Plot", "Metric")) %>% 
              kable_styling(fixed_thead = TRUE, bootstrap_options = 'condensed',
                            full_width = TRUE, position = 'right', font_size = 12) %>% 
              row_spec(0:nrow(buffer_long), extra_css = 'border-bottom: 1px solid #000000;') %>% 
              column_spec(1:2, extra_css = "border-left: 1px solid #000000; border-right: 1px solid #000000;") 
        
veglayout_kbl <- kable(prep_data(vegplot_layout, params$site), format = 'html', align = 'c',
                       caption = "<h4>Vegetation Plot Layout</h4>", col.names = "") %>% 
                 kable_styling(fixed_thead = TRUE, bootstrap_options = 'condensed',
                               full_width = TRUE, position = 'right', font_size = 12) %>% 
                 row_spec(0:1, extra_css = 'border-bottom: 1px solid #000000;') %>% 
                 column_spec(1, extra_css = "border-left: 1px solid #000000; border-right: 1px solid #000000;") 
```

### EPA NWCA 2016 Site Data for: `r paste(site_df$NWCA_codes[site_df$Local_Name == params$site], site_df$Full_Name[site_df$Local_Name == params$site], sep = ": ")`

<div style="display:grid; grid-template-columns: 45% 15% 45%; grid-row-gap: 0px; align-self:start">
<div class="column-left">
```{r AAchar, echo = F}
AAchar_kbl
```
</div>

<div class="column-center">
</div>

<div class="column-right">
```{r watersamp, echo = F}
waterchar_kbl

buffer_kbl

veglayout_kbl
```
</div>
</div>
